//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu HelloWorldResult z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ConsoleApp1.ServiceReference1.HelloWorldResponse HelloWorld(ConsoleApp1.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ConsoleApp1.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dodawanie", ReplyAction="*")]
        double Dodawanie(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dodawanie", ReplyAction="*")]
        System.Threading.Tasks.Task<double> DodawanieAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Odejmowanie", ReplyAction="*")]
        double Odejmowanie(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Odejmowanie", ReplyAction="*")]
        System.Threading.Tasks.Task<double> OdejmowanieAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mnozenie", ReplyAction="*")]
        double Mnozenie(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mnozenie", ReplyAction="*")]
        System.Threading.Tasks.Task<double> MnozenieAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dzielenie", ReplyAction="*")]
        double Dzielenie(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dzielenie", ReplyAction="*")]
        System.Threading.Tasks.Task<double> DzielenieAsync(double a, double b);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsoleApp1.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsoleApp1.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsoleApp1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsoleApp1.ServiceReference1.WebService1Soap>, ConsoleApp1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.ServiceReference1.HelloWorldResponse ConsoleApp1.ServiceReference1.WebService1Soap.HelloWorld(ConsoleApp1.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsoleApp1.ServiceReference1.HelloWorldRequest inValue = new ConsoleApp1.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ConsoleApp1.ServiceReference1.HelloWorldRequestBody();
            ConsoleApp1.ServiceReference1.HelloWorldResponse retVal = ((ConsoleApp1.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.HelloWorldResponse> ConsoleApp1.ServiceReference1.WebService1Soap.HelloWorldAsync(ConsoleApp1.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ConsoleApp1.ServiceReference1.HelloWorldRequest inValue = new ConsoleApp1.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ConsoleApp1.ServiceReference1.HelloWorldRequestBody();
            return ((ConsoleApp1.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public double Dodawanie(double a, double b) {
            return base.Channel.Dodawanie(a, b);
        }
        
        public System.Threading.Tasks.Task<double> DodawanieAsync(double a, double b) {
            return base.Channel.DodawanieAsync(a, b);
        }
        
        public double Odejmowanie(double a, double b) {
            return base.Channel.Odejmowanie(a, b);
        }
        
        public System.Threading.Tasks.Task<double> OdejmowanieAsync(double a, double b) {
            return base.Channel.OdejmowanieAsync(a, b);
        }
        
        public double Mnozenie(double a, double b) {
            return base.Channel.Mnozenie(a, b);
        }
        
        public System.Threading.Tasks.Task<double> MnozenieAsync(double a, double b) {
            return base.Channel.MnozenieAsync(a, b);
        }
        
        public double Dzielenie(double a, double b) {
            return base.Channel.Dzielenie(a, b);
        }
        
        public System.Threading.Tasks.Task<double> DzielenieAsync(double a, double b) {
            return base.Channel.DzielenieAsync(a, b);
        }
    }
}
